import React from 'react';
import { X, ShieldAlert, FileText, Info, Mail, Scale } from 'lucide-react';

interface LegalModalProps {
  page: 'about' | 'privacy' | 'terms' | 'disclaimer' | 'contact' | null;
  onClose: () => void;
  onOpenFeedback?: () => void;
}

export const LegalModal: React.FC<LegalModalProps> = ({ page, onClose, onOpenFeedback }) => {
  if (!page) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 overflow-y-auto bg-slate-900/60 backdrop-blur-sm">
      <div
        className="w-full max-w-2xl bg-white dark:bg-slate-900 rounded-2xl shadow-2xl border border-slate-200 dark:border-slate-800 overflow-hidden flex flex-col max-h-[85vh]"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between bg-slate-50 dark:bg-slate-800/80">
          <div className="flex items-center gap-2.5">
            {page === 'about' && <Info className="w-5 h-5 text-blue-600 dark:text-blue-400" />}
            {page === 'privacy' && <ShieldAlert className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />}
            {page === 'terms' && <Scale className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />}
            {page === 'disclaimer' && <ShieldAlert className="w-5 h-5 text-amber-600 dark:text-amber-400" />}
            {page === 'contact' && <Mail className="w-5 h-5 text-purple-600 dark:text-purple-400" />}
            <h3 className="text-lg font-bold text-slate-900 dark:text-white capitalize">
              {page === 'about' && 'About SmartTools Hub'}
              {page === 'privacy' && 'Privacy Policy'}
              {page === 'terms' && 'Terms of Service'}
              {page === 'disclaimer' && 'Disclaimer & Financial / Health Estimates'}
              {page === 'contact' && 'Contact & Feedback'}
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 rounded-lg hover:bg-slate-200/60 dark:hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 overflow-y-auto space-y-4 text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
          {page === 'about' && (
            <>
              <p className="font-semibold text-slate-900">
                Welcome to SmartTools Hub — The modern all-in-one calculation, conversion, and data utility hub.
              </p>
              <p>
                Our mission is simple: eliminate clunky, ad-cluttered calculators and provide lightning-fast, high-precision tools for finance, salary, tax, business, engineering, health, students, and everyday life.
              </p>
              <h4 className="font-bold text-slate-900 pt-2">Universal PDF Export Innovation</h4>
              <p>
                Unlike traditional calculation websites where you must copy-paste or take screenshots, <strong>every calculator and utility on SmartTools Hub can generate a formatted, professional PDF report</strong> in a single click — completely client-side in your browser for zero latency and total data privacy.
              </p>
              <h4 className="font-bold text-slate-900 pt-2">Privacy & Accessibility First</h4>
              <p>
                SmartTools Hub requires no registration, no account creation, and stores your calculations solely on your local device. It is built to be fast, responsive, and accessible on any smartphone, tablet, or desktop.
              </p>
            </>
          )}

          {page === 'disclaimer' && (
            <>
              <div className="p-4 bg-amber-50 border border-amber-200 rounded-xl text-amber-900">
                <strong>Important Notice:</strong> All calculators, converters, tables, and downloadable PDF reports generated by SmartTools Hub are provided strictly for educational, informational, and personal planning purposes.
              </div>
              <h4 className="font-bold text-slate-900 pt-2">Financial & Tax Calculations</h4>
              <p>
                Calculations for Loan EMI, SIP, Compound Interest, Income Tax (Old vs. New Regime), Gratuity, HRA, and GST rely on mathematical formulas and applicable baseline tax rules. Actual loan approvals, interest rates, tax liabilities, or employer benefits may vary depending on official tax laws, lender terms, and individual circumstances. Consult a Certified Financial Planner (CFP) or Chartered Accountant (CA).
              </p>
              <h4 className="font-bold text-slate-900 pt-2">Health & Fitness Calculations</h4>
              <p>
                Health indicators including BMI, BMR, TDEE, water intake, and caloric deficit calculations are statistical approximations based on demographic equations (e.g. Mifflin-St Jeor formula). They do not constitute medical diagnosis, clinical consultation, or dietetic prescription.
              </p>
            </>
          )}

          {page === 'privacy' && (
            <>
              <p>
                <strong>Privacy is our founding principle.</strong> SmartTools Hub does not require account creation, logins, or submission of personally identifiable data.
              </p>
              <h4 className="font-bold text-slate-900 pt-2">Local Device Processing</h4>
              <p>
                All calculations, graph renders, and PDF exports are processed client-side within your browser JavaScript engine. Your financial figures, loan amounts, salary inputs, or personal dates are not transmitted to or stored on our servers.
              </p>
              <h4 className="font-bold text-slate-900 pt-2">Local Storage</h4>
              <p>
                We use browser localStorage solely to remember your favorite tools, recently accessed calculators, and theme preferences. You can clear this data at any time via your browser settings.
              </p>
              <h4 className="font-bold text-slate-900 pt-2">Third-Party Advertising & Analytics</h4>
              <p>
                To keep this service free for millions of users worldwide, non-intrusive advertisements (such as Google AdSense) may be displayed in designated placement zones. These providers may use anonymous cookies in accordance with their respective privacy policies.
              </p>
            </>
          )}

          {page === 'terms' && (
            <>
              <p>
                By using SmartTools Hub (&quot;the Website&quot;), you agree to these Terms of Service. If you do not agree, please discontinue use of the site.
              </p>
              <h4 className="font-bold text-slate-900 pt-2">Permitted Use</h4>
              <p>
                You are granted a revocable, non-exclusive license to use the calculators, converters, and export PDF/CSV files for your personal, academic, or commercial business planning.
              </p>
              <h4 className="font-bold text-slate-900 pt-2">No Warranty</h4>
              <p>
                The services and calculation formulas are provided &quot;as is&quot; without warranty of any kind. SmartTools Hub disclaims all liability for any loss, damage, or discrepancy arising from the use of calculation outputs.
              </p>
            </>
          )}

          {page === 'contact' && (
            <>
              <p>
                Have a suggestion for a new calculator, found a formula discrepancy, or want to report any problem? We welcome all feedback and respond promptly!
              </p>
              <div className="p-4 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl space-y-3">
                <div className="flex items-center justify-between flex-wrap gap-2">
                  <div>
                    <span className="text-[10px] uppercase font-bold text-slate-400 dark:text-slate-500 tracking-wider block">
                      Official Customer Support & Inquiries
                    </span>
                    <a
                      href="mailto:s94094838@gmail.com"
                      className="text-sm font-bold text-blue-600 dark:text-blue-400 hover:underline"
                    >
                      s94094838@gmail.com
                    </a>
                  </div>
                  <a
                    href="mailto:s94094838@gmail.com?subject=SmartTools%20Hub%20Inquiry"
                    className="px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-xs font-semibold transition-colors flex items-center gap-1.5"
                  >
                    <Mail className="w-3.5 h-3.5" />
                    <span>Send Email</span>
                  </a>
                </div>
                <div className="pt-2 border-t border-slate-200 dark:border-slate-700 text-xs text-slate-500 dark:text-slate-400 space-y-1">
                  <p>
                    <strong>Response Time:</strong> Typically within 24 business hours.
                  </p>
                  <p>
                    <strong>Feature Requests:</strong> We continuously add calculators, PDF layouts, and conversion tools based directly on user submissions.
                  </p>
                </div>
                {onOpenFeedback && (
                  <div className="pt-2">
                    <button
                      type="button"
                      onClick={() => {
                        onClose();
                        onOpenFeedback();
                      }}
                      className="w-full py-2 px-3 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-bold text-xs rounded-xl shadow-xs transition-all flex items-center justify-center gap-2 cursor-pointer"
                    >
                      <span>Open In-App Feedback Form</span>
                    </button>
                  </div>
                )}
              </div>
            </>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/80 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-slate-800 dark:bg-slate-700 hover:bg-slate-900 dark:hover:bg-slate-600 text-white rounded-xl text-xs font-semibold transition-colors cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
